[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['cd backend && pip install -r requirements.txt']

[phases.build]
cmds = ['cd backend && python create_model.py']

[start]
cmd = 'cd backend && python app.py'