services:
  - type: web
    name: health-assistant-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: cd backend && pip install -r requirements.txt && python create_model.py
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
